input {
  file {
    path => "/Users/swaralidegaonkar/Desktop/MLOps/Lab1/MLOps-Labs/ELK_Labs/Lab2_ELK_Setup_Mac/lab6_training.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:log_timestamp} - %{LOGLEVEL:log_level} - %{GREEDYDATA:log_message}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "lab6-logstash-training"
  }
  stdout {
    codec => rubydebug {
      metadata => false
    }
  }
}